// api/quotes.js
import { fetchLiveQuotes } from './_shared.js';
// const RAW_SYMBOLS = `AARTIIND,ABB,ABBOTINDIA,ABCAPITAL,ABFRL,ACC,ADANIENT,ADANIPORTS,ALKEM,AMARAJABAT,AMBUJACEM,APOLLOHOSP,APPLAPOLLO,ASHOKLEY,ASIANPAINT,ASTRAL,ATUL,AUBANK,AUROPHARMA,AXISBANK,BAJAJ-AUTO,BAJAFINSV,BAJFINANCE,BALKRISIND,BALRAMCHIN,BANDHANBNK,BANKBARODA,BATAINDIA,BEL,BHARATFORG,BHARTIARTL,BHEL,BIOCON,BLUESTARCO,BOSCHLTD,BPCL,BRITANNIA,BSE,CAMS,CANBK,CDSL,CESC,CGPOWER,CHOLAFIN,CIPLA,COALINDIA,COFORGE,COLPAL,CONCOR,CROMPTON,CUMMINSIND,CYIENT,DABUR,DALBHARAT,DELV,DIVISLAB,DIXON,DLF,DMART,DRREDDY,EICHERMOT,ETERNAL,EXIDEIND,FEDERALBNK,FORTIS,GAIL,GLENMARK,GMRAIRPORT,GODREJCP,GODREJPROP,GRANULES,GRASIM,HAL,HAVELLS,HCLTECH,HDFCBANK,HDFCAMC,HDFCLIFE,HEROMOTOCO,HFCL,HINDALCO,HINDPETRO,HINDUNILVR,HINDZINC,HUDCO,ICICIBANK,ICICIGI,ICICIPRULI,IDEA,IDFCFIRSTB,IEX,IGL,IIFL,INDHOTEL,INDIANB,INDIGO,INDUSINDBK,INDUSTOWER,INFY,INXWIND,IOC,IRB,IRCTC,IREDA,IRFC,ITC,JINDALSTEL,JIOFIN,JSL,JSWENERGY,JSWSTEEL,JUBLFOOD,KALYANKJIL,KAYNES,KEI,KFINTECH,KOTAKBANK,KPITTECH,LAURUSLABS,LICHSGFIN,LICI,LODHA,LT,LTF,LTIM,LUPIN,M&M,MANAPPURAM,MANKIND,MARICO,MARUTI,MAXHEALTH,MAZDOCK,MCX,MFSL,MOTHERSON,MPHASIS,MUTHOOTFIN,NALCO,NAUKRI,NBCC,NCC,NESTLEIND,NHPC,NMDC,NTPC,NUVAMA,NYKAA,OBEROIRLTY,OFSS,OIL,ONGC,PAGEIND,PATANJALI,PAYTM,PERSISTENT,PETRONET,PFC,PGEL,PHOENIXLTD,PIDILITIND,PIIND,PNB,PNBHOUSING,POLICYBZR,POLYCAB,POONAWALLA,POWERGRID,PPLPHARMA,PRESTIGE,RBLBANK,RECLTD,RELIANCE,RVNL,SAIL,SBICARD,SBILIFE,SBIN,SHREECEM,SHRIRAMFIN,SIEMENS,SJVN,SOLARINDS,SONACOMS,SRF,SUNPHARMA,SUPREMEIND,SUZLON,SYNGENE,TATACHEM,TATACONSUM,TATAELXSI,TATAMOTORS,TATAPOWER,TATASTEEL,TATATECH,TCS,TECHM,TIINDIA,TITAGARH,TITAN,TORNTPHARM,TORNTPOWER,TRENT,TVSMOTOR,ULTRACEMCO,UNIONBANK,UNITDSPR,UNOMINDA,UPL,VBL,VEDL,VOLTAS,WIPRO,YESBANK,ZYDUSLIFE,360ONE,BDL,DELHIVERY,ZOMATO,ADANIGREEN,ADANIENSOL,ATGL,`;

export default async function handler(req, res) {
  try {
    // ✅ Allow only POST method
    if (req.method !== 'POST') {
      return res.status(405).json({ error: 'Method Not Allowed. Use POST.' });
    }

    // ✅ Handle CORS headers
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'POST, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');
    res.setHeader('Cache-Control', 'no-store');

    // ✅ Parse JSON body
    let body = '';
    await new Promise((resolve) => {
      req.on('data', (chunk) => (body += chunk));
      req.on('end', resolve);
    });

    const { symbols } = JSON.parse(body || '{}');

    if (!symbols) {
      return res
        .status(400)
        .json({ error: 'symbols field required in request body' });
    }

    console.log('[devServer] /api/quotes (POST symbols):', symbols);

    // ✅ Fetch snapshot
    const snapshot = await fetchLiveQuotes(symbols);

    return res.status(200).json(snapshot);
  } catch (err) {
    console.error('QUOTES_ERROR', err);
    return res
      .status(500)
      .json({ error: err?.message || String(err) || 'Unknown error' });
  }
}
